title: "Nicolas Hery - Web development, data analytics"
description: >
  Nicolas Hery is a freelance web developer based in Paris, France. He has a
  background in applied mathematics, works as a full-stack developer mostly in
  JavaScript and Node.js, as well as Python for scientific computing.
baseurl: ""
url: "http://nicolashery.com"

markdown: redcarpet
permalink: /:title/
exclude:
- Gemfile
- Gemfile.lock
- README.md
- env
- s3_website.yml
- tmp

sass:
  style: compressed

images:
  root_url: "/img"

disqus:
  shortname: "nicolashery"
