name: 'Nicolas Hery'
description: 'Web development. Data analytics.'
url: 'http://nicolashery.com'

markdown: redcarpet
pygments: true
permalink: /:title/
exclude: [
  'node_modules',
  'bower_components',
  'Gruntfile.js',
  'package.json',
  'bower.json',
  'requirements.txt',
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'css',
  'sass',
  'js',
  'coffee',
  'env',
  'tmp'
]

assets:
  root_url: '/assets'

images:
  root_url: '/assets/img'

disqus:
  shortname: 'nicolashery'
