title: "Nicolas Hery - Software Developer"
description: >
  Nicolas Hery is a software developer based in Montreal. He works with a variety
  of programming languages and platforms to design and implement technical solutions
  to real business problems.
baseurl: ""
url: "http://nicolashery.com"

permalink: /:title/
exclude:
- README.md
- env
- s3_website.yml
- tmp

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

author:
  twitter: nicolas_hery

sass:
  style: compressed
  sourcemap: development

images:
  root_url: "/img"

disqus:
  shortname: "nicolashery"
